
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @flow
 *
 * @generated by codegen project: GenerateViewConfigJs.js
 */

'use strict';

const NativeComponentRegistry = require('react-native/Libraries/NativeComponent/NativeComponentRegistry');
const {ConditionallyIgnoredEventHandlers} = require('react-native/Libraries/NativeComponent/ViewConfigIgnore');

let nativeComponentName = 'RCTSpinWheel';


export const __INTERNAL_VIEW_CONFIG = {
  uiViewClassName: 'RCTSpinWheel',

  bubblingEventTypes: {
    topSpinEnd: {
      phasedRegistrationNames: {
        captured: 'onSpinEndCapture',
        bubbled: 'onSpinEnd',
      },
    },
  },

  validAttributes: {
    configUrl: true,

    ...ConditionallyIgnoredEventHandlers({
      onSpinEnd: true,
    }),
  },
};

export default NativeComponentRegistry.get(nativeComponentName, () => __INTERNAL_VIEW_CONFIG);
